apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: easylb-controller
  name: easylb-system:easylb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: easylb-system:easylb-controller
subjects:
- kind: ServiceAccount
  name: easylb-controller
  namespace: easylb-system